### ISSUE TITLE
04 TODO

### ISSUE THREAD

**Issue by kimsintae** [kimsintae/ALA#5]
1. 화면정의
https://docs.google.com/presentation/d/1Tz4dqEagE4NMHKuqGuomT-raMp86q40CSlOVzqmjQCE/edit#slide=id.p

2. 기능정의
3. ERD 정의
4. API 명세
5. 퍼블리싱
6. DB 구축
7. 프레임워크 구축
8. 개발

**Comment by kimsintae** [comment]
우선순위


*장비
- 노트북(서버용)

1. 환경구축

- [ ] 도커환경 셋팅(로컬테스트후)
- [x] 컨테이너 셋팅(웹서비스 4개) - 아키텍쳐 재구성 필요
- [x] API Gateway 셋팅
- [ ] Spring config 셋팅
- [ ] security 셋팅(jwt) - 적용 및 테스트
- [ ] 오케스트레이션 적용(스웜)

2. 데이터베이스 셋팅
-> ERD 그리기
-> DB 설치 
-> 데이터 정제 및 테이블 생성
3. 서비스 구현
